### PR TITLE
Add cmakelists, getoptw lib for msvc

### PR DESCRIPTION
**Pull request by ARM9**
I was able to make debug and release builds with both mingw and vc++ on windows with this cmakelist. Haven't tested it on OS X.

The getoptw library is LGPL, I added it to get visual studio builds working since Microsoft doesn't provide a getopt implementation.

### CODE REVIEW

**Comment by Optiroc** [comment]
@ARM9 I'm so lost with Windows... Do you know what steps are needed to make the VS2017 tool chain visible to CMake? My hope was that CMake would look for the compiler in known places, but it fails with the message `CMake Error in : No CMAKE_CXX_COMPILER could be found`.

**Comment by ARM9** [comment]
Can you gist the generated CMakeError.log?

**Comment by Optiroc** [comment]
After some troubleshooting I got it to build with the MS toolchain (I was missing the Windows 8.1 SDK and Windows Universal C Runtime packages). Great! Binary size went from 12MB to 380KB.

**Comment by Optiroc** [comment]
I published a release with Windows builds. Now I just need to do the homework required to automate Windows 32- and 64-bit builds without needing to open Visual Studio...

**Pull request merged**
